# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%y%m%d"

  - trigger: ":kvk"
    replace: "75313685"

  - trigger: ":btw"
    replace: "NL860234241B01"

  - trigger: ":iban"
    replace: "NL25ABNA0854555366"

  - trigger: ":swift"
    replace: "ABNANL2A"

  - trigger: ":color"
    replace: "#00B1E9"
    
